services:
  windows:
    image: dockurr/windows
    container_name: windows-server-2022
    environment:
      VERSION: "win2022-eval"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8007:8006
      - 4489:3389/tcp
      - 4489:3389/udp
    volumes:
      - ./windows:/storage
    restart: always
    stop_grace_period: 2m
